//@version=5
strategy("MA+威廉姆斯",overlay=true,initial_capital=1000,default_qty_type = strategy.cash,default_qty_value = 2000)

var start_ts            =   timestamp('2024-05-01T12:00:00+0800')
cfg_start_time_enable   =   input.bool(false            ,''                 ,inline='start_time')
cfg_start_time          =   input.time(start_ts         ,'开始时间'         ,inline='start_time')

// ============================ ma ============================ 
ma(source, length, type) =>
    type == "SMA" ? ta.sma(source, length) :
     type == "EMA" ? ta.ema(source, length) :
     type == "SMMA (RMA)" ? ta.rma(source, length) :
     type == "WMA" ? ta.wma(source, length) :
     type == "VWMA" ? ta.vwma(source, length) :
     na

show_ma1   = input(true   , "MA №1", inline="MA #1", display = display.data_window)
ma1_type   = input.string("EMA"  , ""     , inline="MA #1", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma1_source = input(close  , ""     , inline="MA #1", display = display.data_window)
ma1_length = input.int(25     , ""     , inline="MA #1", minval=1)
ma1_color  = input(#f6c309, ""     , inline="MA #1", display = display.data_window)
ma1 = ma(ma1_source, ma1_length, ma1_type)
plot(show_ma1 ? ma1 : na, color = ma1_color, title="MA №1")

show_ma2   = input(true   , "MA №2", inline="MA #2", display = display.data_window)
ma2_type   = input.string("SMA"  , ""     , inline="MA #2", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma2_source = input(close  , ""     , inline="MA #2", display = display.data_window)
ma2_length = input.int(50     , ""     , inline="MA #2", minval=1)
ma2_color  = input(#fb9800, ""     , inline="MA #2", display = display.data_window)
ma2 = ma(ma2_source, ma2_length, ma2_type)
plot(show_ma2 ? ma2 : na, color = ma2_color, title="MA №2")

show_ma3   = input(true   , "MA №3", inline="MA #3", display = display.data_window)
ma3_type   = input.string("SMA"  , ""     , inline="MA #3", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma3_source = input(close  , ""     , inline="MA #3", display = display.data_window)
ma3_length = input.int(100    , ""     , inline="MA #3", minval=1)
ma3_color  = input(#fb6500, ""     , inline="MA #3", display = display.data_window)
ma3 = ma(ma3_source, ma3_length, ma3_type)
plot(show_ma3 ? ma3 : na, color = ma3_color, title="MA №3")

show_ma4   = input(true   , "MA №4", inline="MA #4", display = display.data_window)
ma4_type   = input.string("SMA"  , ""     , inline="MA #4", options=["SMA", "EMA", "SMMA (RMA)", "WMA", "VWMA"])
ma4_source = input(close  , ""     , inline="MA #4", display = display.data_window)
ma4_length = input.int(200    , ""     , inline="MA #4", minval=1)
ma4_color  = input(#f60c0c, ""     , inline="MA #4", display = display.data_window)
ma4 = ma(ma4_source, ma4_length, ma4_type)
plot(show_ma4 ? ma4 : na, color = ma4_color, title="MA №4")

// ============================ ma trend ============================ 
strong_long_trend = ma1 > ma2 and (ma1 > ma2 and ma2 > ma3) and (ma1 > ma2 and ma2> ma3 and ma3 > ma4) // 强多头趋势
secondary_long_trend = ma1 > ma2 and ma2 > ma3 and ma3 < ma4 // 次多头趋势
long_trend = ma1 > ma2 and ma2 < ma3 and ma3 > ma4 // 不确定
weak_long_trend = ma1 > ma2 and ma2 < ma3 and ma3 < ma4 // 弱多头趋势

weak_short_trend = ma1 < ma2 and ma2 > ma3 and ma3 > ma4 // 弱空头趋势
short_trend = ma1 < ma2 and ma2 > ma3 and ma3 < ma4 // 不确定
secondary_short_trend = ma1 < ma2 and ma2 < ma3 and ma3 > ma4 // 次空头趋势
strong_short_trend = ma1 < ma2 and (ma1 < ma2 and ma2 < ma3) and (ma1 < ma2 and ma2 < ma3 and ma3 < ma4) // 强空头趋势


// 威廉姆斯
type short_hl_obj
    int dir             //1高点  -1低点
    chart.point left    //左
    chart.point mid     //中
    chart.point right   //右
    int node_count=0
    short_hl_obj pre

// 所有的短期高点
var all_short_top=array.new<short_hl_obj>()
// 所有的短期低点
var all_short_bot=array.new<short_hl_obj>()

new_top=high<high[1] and high[1]>high[2]
new_bot=low>low[1] and low[1]<low[2]

fun_process_new_short_hl()=>
    if new_top
        left =chart.point.new(time[2],bar_index[2],high[2])
        mid  =chart.point.new(time[1],bar_index[1],high[1])
        right=chart.point.new(time[0],bar_index[0],high[0])
        all_short_top.unshift(short_hl_obj.new(1,left,mid,right))

    if new_bot
        left =chart.point.new(time[2],bar_index[2],low[2])
        mid  =chart.point.new(time[1],bar_index[1],low[1])
        right=chart.point.new(time[0],bar_index[0],low[0])
        all_short_bot.unshift(short_hl_obj.new(-1,left,mid,right))

fun_process_new_short_hl()

// 入场点 强趋势可以入场

ps=strategy.position_size

var point_long = false
if all_short_bot.size()>=2
    point_long := (all_short_bot.get(0).mid.price>all_short_bot.get(1).mid.price) and (close > all_short_top.get(0).mid.price)

var point_short = false
if all_short_top.size()>=2
    point_short := (all_short_top.get(0).mid.price<all_short_top.get(1).mid.price) and (close < all_short_bot.get(0).mid.price)

long_signal  = point_long 
short_signal = point_short

if ps == 0
	if strong_long_trend and point_long
		strategy.entry('long', strategy.long,comment = '做多',stop = all_short_bot.get(0).mid.price,oca_name = 'entry',oca_type = strategy.oca.cancel)
	if strong_short_trend and point_short
		strategy.entry('short',strategy.short,comment = '做空',stop = all_short_top.get(0).mid.price,oca_name = 'entry',oca_type = strategy.oca.cancel)
else
	if ps > 0
		// 
		higest_low_point = ma1 > all_short_bot.get(0).mid.price ? all_short_bot.get(0).mid.price:ma1
		//higest_low_point = (all_short_bot.get(0).mid.price+ma1) / 2
		strategy.exit('exit long','long',stop=higest_low_point,comment_loss ='多离场')
	else
		lowest_high_point = ma1 > all_short_top.get(0).mid.price ?all_short_top.get(0).mid.price:ma1
		//lowest_high_point = (all_short_top.get(0).mid.price+ma1) / 2
		strategy.exit('exit short','short',stop=lowest_high_point,comment_loss = '空离场')
